### ISSUE TITLE
Getting started and ticket 1

### ISSUE THREAD

**Issue by HopeIvy12** [SchoolOfCode/week-3-intro-to-the-dom-hohoho#1]
```[tasklist]
### connecting
- [x] Make Js file and connect
- [x] check js is linked
```

```[tasklist]
### Tasks
- [x] getElementById() to select the element with the id of "title"
- [x] getElementsByClassName() to select elements with the class of "content"
- [x] getElementsByTagName() to select all <li> elements on the page.
- [x] querySelector() to select the first element with the class "highlight".
- [x] Use querySelectorAll() to select all elements with the class "highlight".
```
