### ISSUE TITLE
ticket 2

### ISSUE THREAD

**Issue by HopeIvy12** [SchoolOfCode/week-3-intro-to-the-dom-hohoho#2]
```[tasklist]
### Tasks
- [ ] Parent Node: first <li> element inside the <ul> with the id of "itemList. We have used parent.Node
- [ ] Select <ul> element with the id of "itemList". Use the childNodes property to get all its child nodes.
- [ ] Select the <ul> element with the id of "itemList". Use the children property to get all its element children.
- [ ] Select the <ul> element with the id of "itemList". Use the firstChild and lastChild properties to get the first and last child nodes.
```
